title: "Fabio & Carlotta"
baseurl: ""
url: "https://www.fabioecarlotta.it"
markdown: kramdown
theme: null

wedding:
  couple_names: "Fabio & Carlotta"
  date_en: "20th of June 2026"
  date_it: "20 giugno 2026"
  location_line1: "Villa Pellegrini"
  location_line2: "Romagnano di Valpantena, Verona"
  rsvp_link: ""

github_username: fabiolucidi
repository: fabiolucidi/fabioecarlotta.github.io
repo_url: https://github.com/fabiolucidi/fabioecarlotta.github.io


i18n:
  it:
    nav:
      home: "Home"
      story: "Storia"
      where_when: "Cerimonia e Party"
      rsvp: "RSVP"
      where_stay: "Dove dormire"
      qa: "Q&A"
    sections:
      story: "Storia"
      where_when: "Cerimonia e Party"
      rsvp: "RSVP"
      where_stay: "Dove dormire"
      qa: "Q&A"

  en:
    nav:
      home: "Home"
      story: "Story"
      where_when: "Where & When"
      rsvp: "RSVP"
      where_stay: "Where to Stay"
      qa: "Q&A"
    sections:
      story: "Story"
      where_when: "Where & When"
      rsvp: "RSVP"
      where_stay: "Where to Stay"
      qa: "Q&A"
